### ISSUE TITLE
Tamper suggesting

### ISSUE THREAD

**Issue by S0me1-dev** [stamparm/identYwaf#13]
Hello, Stamparm. Can you plz add tamper suggesting(testing) for sqlmap like it realized in WhatWaf https://github.com/Ekultek/WhatWaf and maybe integrate this cool tool in sqlmap

**Comment by stamparm** [comment]
1) He literary stole all the work from sqlmap. I have a bad history with that faker where I openly accused him for doing that and not referencing the sqlmap for anything
2) Identywaf is incorporated into sqlmap for some time till now. At some point in time I will most probably do some tamper suggesting, but that problem is not an easy one. This basically means that tamper suggesting is something that won't go into identywaf, but eventually inside the sqlmap.

**Comment by S0me1-dev** [comment]
https://github.com/m4ll0k/Atlas Here is one more tamper suggester. Thats 2 tools which sometimes realy help , and hope someday it will be realised in original tool. Thanks for answer and your work. 
And of course its not good to dont countribute and reference tool wich code you use (

**Comment by S0me1-dev** [comment]
import os
import re
import requests
from random import choice
from sqlmap import sqlmap
from sqlmap import module

class TamperSuggester(module.Tamper):
    """
    Tamper class for suggesting and testing different tamper scripts
    """
    def __init__(self):
        self.tampers = []
        self.tested_tampers = []
        self.last_payload = ""
        self.stop_scan = False
        self.current_index = 0
        self.results = {}
        self.bad_status_codes = [400, 401, 403, 404, 500]

    def suggest_tampers(self):
        """
        Suggest available tamper scripts
        """
        for file_name in os.listdir("tamper"):
            if file_name.endswith(".py"):
                self.tampers.append(file_name[:-3])
                self.results[file_name[:-3]] = {}

    def test_tamper(self, tamper_name, payload=None):
        """
        Test a specific tamper script
        """
        if tamper_name not in self.tampers:
            print("[ERROR] Invalid tamper script '%s'" % tamper_name)
            return
        try:
            module = __import__("tamper.%s" % tamper_name, fromlist=["tamper"])
            try:
                tamper = module.tamper()
                if not hasattr(tamper, 'tamper'):
                    print("[ERROR] Tamper script does not have a tamper() method")
                    return
                payload = tamper.tamper(self.last_payload) if payload is None else tamper.tamper(payload)
                req = requests.get(sqlmap.url, params=payload)
                self.results[tamper_name]['status_code'] = req.status_code
                self.results[tamper_name]['payload'] = payload
if req.status_code != sqlmap.last_status_code:
print("[INFO] Tamper '%s' seems to be working" % tamper_name)
self.tested_tampers.append(tamper_name)
if req.status_code in self.bad_status_codes:
self.stop_scan = True
user_input = input("[INFO] Bad status code %s received. Continue scanning with tamper suggestions? (yes/no/later)")
if user_input.lower() == "yes":
self.handle_bad_response()
elif user_input.lower() == "no":
self.stop_scan = True
else:
self.stop_scan = False

def handle_bad_response(self):
"""
Handle bad status code response
"""
self.tested_tampers.pop()
self.test_random_tamper()

def start_scan(self):
"""
Start scanning with tamper suggestions
"""
self.suggest_tampers()
while self.current_index < len(self.tampers) and not self.stop_scan:
self.test_random_tamper()
self.current_index += 1

def get_results(self):
"""
Get results of tamper testing
"""
return self.results

def get_tested_tampers(self):
"""
Get list of tested tampers
"""
return self.tested_tampers



I am noob in py, but I think the sceleton of that function might be something like that. 
User start sqlmap with tamper=tmpsgstr it analyze payload and responses . Maybe someone will help in improvement. There is a many ways to made a new logic , functions and etc in that tamper suggester. 

We need for shure that function. There is a nice try to bypass waf I think. 


-
Also there is a flaresolverr tool to complete cloudflare checks, (but it's another story)
