### ISSUE TITLE
baidu DuEdge waf

### ISSUE THREAD

**Issue by c2xusnpq6** [stamparm/identYwaf#14]
`DuEdge Event ID\:`
http://www.lequgo.com/shopping-nav/index.aspx?sort=1%27&classid=1
![圖片](https://user-images.githubusercontent.com/75058881/103440211-bb7c2e00-4c7e-11eb-9b8a-0cd1d8af2504.png)

**Comment by c2xusnpq6** [comment]
google: The current visit may pose a security threat, and your visit is blocked. Attack type: [application vulnerability attack]
bing: Current access can pose a security threat and your access is blocked. Type of attack: Application Vulnerability Attack

**Comment by stamparm** [comment]
Thank you for your report. Added this one, although it doesn't seem like a typical WAF. Typical WAF would trigger immediately on anything that looks like an obvious attack, while in this case it triggers here and there on some trivial attempts (e.g. single-quote injection)
