### ISSUE TITLE
about chinese waf products

### ISSUE THREAD

**Issue by c2xusnpq6** [stamparm/identYwaf#15]
You may want to add some Chinese words as a condition to recognize WAF, since many Chinese websites are only for Chinese people, they are set to display only Chinese.

like this one: aliyundun (from alibaba's aliyun) 
`很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断` or ( `您的请求ID是` and ( http status=`405` or title=`405` )
![image](https://user-images.githubusercontent.com/75058881/112844787-b4768780-90d6-11eb-99a7-c19cfd9348a4.png)
![image](https://user-images.githubusercontent.com/75058881/112844842-c0624980-90d6-11eb-9b46-cdb0dc012bfe.png)
![image](https://user-images.githubusercontent.com/75058881/112844901-d112bf80-90d6-11eb-95ac-783e3f485454.png)

https://github.com/stamparm/identYwaf/blob/70a830909148b551d11294a15c8ad01bf7317aa6/data.json#L87
I think you might want to know this, so...~

**Comment by c2xusnpq6** [comment]
360? tencent? baidu? meituan? these chinese big company have their own cloud services, you may want to take a look

**Comment by c2xusnpq6** [comment]
sometimes, even that the error page have eng ver, and your browser lang: `eng` but it still display chinese, not eng

**Comment by stamparm** [comment]
I am always trying to "target" only the strings that can appear inside the response. Pretty sure that majority is covered properly.

Will take a look for `aliyundun`, but please do not over-extend this without any proper proof/use case

**Comment by stamparm** [comment]
double checked. that regex you've mentioned has two disjunct conditions. the second one is `//errors\\.aliyun\\.com/`. That one is appearing in Chinese response too. Closing this down

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/113118087-6913c480-920f-11eb-9179-4927996e9bea.png)

p.s. please don't open issues without a proper "proof"
