### ISSUE TITLE
China Telecom CDN `CtYun`

### ISSUE THREAD

**Issue by c2xusnpq6** [stamparm/identYwaf#19]
header:
```
ctyun-origin: 211
Ctyun_Cdn_Gateway: v3.4.0
```

https://censys.io/ipv4
https://www.shodan.io/
https://www.zoomeye.org/
https://fofa.so/
https://quake.360.cn/quake/#/index

**Comment by c2xusnpq6** [comment]
`天翼云` = `CtYun`

**Comment by stamparm** [comment]
1) CDN is not WAF
2) I don't see a "reactive" component here (something that is used to "protect" from attacks), based on tests on sites found
