### ISSUE TITLE
why move flags to the beginning of the WAF_RECOGNITION_REGEX?

### ISSUE THREAD

**Issue by lineuman** [stamparm/identYwaf#20]
https://github.com/stamparm/identYwaf/blob/c623194fb1d4c4686929e251433b652fbbfdbd59/identYwaf.py#L353

i don't understand why move the flags to the beginning of the WAF_RECOGNITION_REGEX?
i just want to match a keyword that case sensitive,but if a waf regex has (?i), it will work to all regex, so why?

thanks.
best wishes for you.

**Comment by lineuman** [comment]
![image](https://user-images.githubusercontent.com/12708732/146192623-d5c7e867-ebd1-48b1-b2d9-43ec86377a39.png)

example of, i just want to match bc, not BC, hope you can understand what i mean

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/146228099-6538731a-fa60-4415-9d00-7c5f27a5d344.png)

**Comment by stamparm** [comment]
Blame it on Python3. They are pretty fast on deprecation -> obsolete/removal of functionality, thus, I had to do this dirty stuff
