### ISSUE TITLE
[Suggestion] Add custom headers for authenticated scan

### ISSUE THREAD

**Issue by ghost** [stamparm/identYwaf#8]
I some webapp you can find custom headers like:
`X-api-token` or similar.
But to check for WAF at the moment there is no option.
This could help a lot.
I can add a PR if you like this idea, when i have some free time.
Awesome project!

**Comment by stamparm** [comment]
WAF should not be behind authenticated mechanism(s). It should be web app agnostic. Hence, have to close this one down
